In [1]:
#Make sure it is importable
import sys
sys.path.append('python')
from NGC5533_functions import * #prevents having to use prefix each time

In [2]:
#Ensure that all constants can be called

#---------Definitely Constant---------
print(G)
print(rhocrit)

#---------Measured Directly-----------
print(L)
print(absmag)
print(magsun)
print(L0)

#---------Measured Indirectly---------
print(ups)
print(q)
print(e2)
print(i)
print(h_rc)
print(c)
print(Mvir)
print(Mbh_def)

#---------Definitely Variable---------
print(n_c)
print(h_c)
print(drho00_c)
print(hrho00_c)

#---------Uncategorized-------------------
print(re_c)
print(epsdisk)
print(rs)
print(rho_s)
print(h_gamma)

4.30091e-06
9.3e-18
32700000000.0
-22.02
4.42
37670379898.39093
2.8
0.33
0.8911
0.7853981633974483
1.4
1e-12
1.7477453551675242e+185
2700000000.0
2.7
8.9
310000000.0
310000000.0
2.6
5.0
3.553329921083743e+78
3.487041255446485e-36
0


In [3]:
#Ensure that saving/loading works outside of functions

savedata([1],[0],'test','test',file='test.hdf5') #Create new file
savedata([1],[0],'test','test1',file='test.hdf5')#Create new dataset
savedata([1],[0],'test1','test',file='test.hdf5')#Create new group
savedata([1],[0],'test','test',file='test.hdf5') #Attempt to create existing
loaddata('test','test',file='test.hdf5')         #Load

array([[1],
       [0]])

In [4]:
#numpy array for use with functions
x = np.linspace(1,10,10)

In [5]:
#Black Hole
#Showing that args are handled without error in variety of combinations
#Done here because this is the fastest calculation

bh_v(1,load=False)                        #Single point, accept default(s), no save or load, no args, no kwargs
bh_v(x,load=False)                        #Multiple points, AD, n, nk
bh_v(1,1,load=False)                      #SP, change M, n, nk
bh_v(x,1,load=False)                      #MP, cM, n, nk
bh_v(1,save=True,load=False)              #SP, AD, save, nk
bh_v(x,save=True,load=False)              #MP, AD, s, nk
bh_v(1,1,save=True,load=False)            #SP, cM, s, nk
bh_v(x,1,save=True,load=False)            #MP, cM, s, nk
bh_v(1,load=True)                         #SP, AD, load, nk
bh_v(x,load=True)                         #MP, AD, l, nk
bh_v(1,1,load=True)                       #SP, cM, l, nk
bh_v(x,1,load=True)                       #MP, cM, l, nk
bh_v(1,file='test',load=False)            #SP, AD, n, kwargs
bh_v(x,file='test',load=False)            #MP, AD, n, k
bh_v(1,1,file='test',load=False)          #SP, cM, n, k
bh_v(x,1,file='test',load=False)          #MP, cM, n, k
bh_v(1,save=True,load=False)              #SP, AD, s, k
bh_v(x,save=True,load=False)              #MP, AD, s, k
bh_v(1,1,save=True,load=False)            #SP, cM, s, k
bh_v(x,1,save=True,load=False)            #MP, cM, s, k
bh_v(1,load=True)                         #SP, AD, l, k
bh_v(x,load=True)                         #MP, AD, l, k
bh_v(1,1,load=True)                       #SP, cM, l, k
bh_v(x,1,load=True)                       #MP, cM, l, k

array([0.00207386, 0.00146644, 0.00119735, 0.00103693, 0.00092746,
       0.00084665, 0.00078385, 0.00073322, 0.00069129, 0.00065581])

In [6]:
#Bulge
#Not going to show every combination this time as all functions mirror each other in structure,
#Especially the velocity functions
b_gammafunc(x)
b_I0()
b_r0()
b_innerintegral(1) #Integration not meant to be called for an array
b_vsquare(1)       #Not yet vectorized
b_vsquarev(x)
b_v(x)
b_v(x,save=True)
b_v(x,load=True)

array([245.1230321 , 246.33088903, 235.84306215, 223.69503285,
       211.99654399, 201.25692665, 191.5450646 , 182.79683978,
       174.91221427, 167.78832117])

In [7]:
#Halo
h_rhat(x,x)
h_rho(x)
h_vcasertano(x,x)
h_vjimenez(x)
h_vNFW(x)
h_viso(x)
h_v(x)
h_v(x,save=True)
h_v(x,load=True)

array([3.30494924e-16, 1.03776329e+02, 1.24329963e+02, 1.36580950e+02,
       1.44588565e+02, 1.50197375e+02, 1.54332991e+02, 1.57503683e+02,
       1.60009716e+02, 1.62039185e+02])

In [8]:
#Disk
z0(1)
R(1)
d(1)
d_px(x,x,x)
d_rho0(x)
d_durho0(x)
d_rho_rz(x,x)
d_drho_rz(x,x)
d_K(x,x,x)
d_innerfunc(x,x,x)
d_innerintegral(1,1)
d_outerintegral(1)
d_Mdblintrho()
d_F(1)
d_v(x,load=False)
d_v(x,save=True,load=False)
d_v(x,load=True)

python/NGC5533_functions.py:374: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  return si.quad(d_innerintegral, 0, np.inf, args=(r,h,d_rho00))[0]


array([119.11679082, 171.07050149, 210.77442111, 243.27634522,
       270.62244314, 293.9458118 , 313.98406245, 331.26634852,
       346.19679878, 359.09744684])

In [9]:
#Total
v(x,load=False)
v(x,save=True,load=False)
v(x,load=True)

python/NGC5533_functions.py:208: RuntimeWarning: divide by zero encountered in double_scalars
  return L*(b_root**(2*n))/(re**2*2*np.pi*n*ss.gamma(2*n))
python/NGC5533_functions.py:213: RuntimeWarning: divide by zero encountered in double_scalars
  f = lambda x,m,n,re: np.exp(-np.power(x/b_r0(n,re), (1/n)))*np.power(x/b_r0(n,re), 1/n-1)/(np.sqrt(x**2-m**2)) #Inner function
python/NGC5533_functions.py:219: RuntimeWarning: invalid value encountered in double_scalars
  h = lambda m,r,n,re: C(n,re)*b_innerintegral(m,n,re)*(m**2)/(np.sqrt((r**2)-((m**2)*(e2)))) #integrate outer function
python/NGC5533_functions.py:220: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return si.quad(h, 0, r, args=(r,n,re))[0]


array([12.67389946, 14.63232087, 15.89014672, 16.85672997, 17.62350455,
       18.24869081, 18.76770129, 19.20356332, 19.57227351, 19.88555007])