In [1]:
#Make sure it is importable
import sys
sys.path.append('python')
from NGC5533_functions import * #prevents having to use prefix each time

In [2]:
#Ensure that all constants can be called

#---------Definitely Constant---------
print(G)
print(rhocrit)

#---------Measured Directly-----------
print(L)
print(absmag)
print(magsun)
print(L0)

#---------Measured Indirectly---------
print(ups)
print(q)
print(e2)
print(i)
print(h_rc)
print(c)
print(Mvir)
print(Mbh_def)

#---------Definitely Variable---------
print(n_c)
print(h_c)
print(drho00_c)
print(hrho00_c)

#---------Uncategorized-------------------
print(re_c)
print(epsdisk)
print(rs)
print(rho_s)
print(h_gamma)

{'limit': 100}
4.30091e-06
9.3e-18
32700000000.0
-22.02
4.42
37670379898.39093
2.8
0.33
0.8911
0.7853981633974483
1.4
1e-12
1.7477453551675242e+185
2700000000.0
2.7
8.9
310000000.0
9.9
5.0
3.553329921083743e+78
3.487041255446485e-36
0


In [3]:
#Ensure that saving/loading works outside of functions

savedata([1],[0],'test','test',file='test.hdf5') #Create new file
savedata([1],[0],'test','test1',file='test.hdf5')#Create new dataset
savedata([1],[0],'test1','test',file='test.hdf5')#Create new group
savedata([1],[0],'test','test',file='test.hdf5') #Attempt to create existing
loaddata('test','test',file='test.hdf5')         #Load

Saved.
Saved.
Saved.
Saved.


array([[1],
       [0]])

In [4]:
#numpy array for use with functions
x = np.linspace(1,10,10)

In [5]:
#Black Hole
#Showing that args are handled without error in variety of combinations
#Done here because this is the fastest calculation

bh_v(1)                        #Single point, accept default(s), no save or load, no args, no kwargs
bh_v(x)                        #Multiple points, AD, n, nk
bh_v(1,1)                      #SP, change M, n, nk
bh_v(x,1)                      #MP, cM, n, nk
bh_v(1,save=True)              #SP, AD, save, nk
bh_v(x,save=True)              #MP, AD, s, nk
bh_v(1,1,save=True)            #SP, cM, s, nk
bh_v(x,1,save=True)            #MP, cM, s, nk
bh_v(1,load=True)              #SP, AD, load, nk
bh_v(x,load=True)              #MP, AD, l, nk
bh_v(1,1,load=True)            #SP, cM, l, nk
bh_v(x,1,load=True)            #MP, cM, l, nk
bh_v(1,file='test')            #SP, AD, n, kwargs
bh_v(x,file='test')            #MP, AD, n, k
bh_v(1,1,file='test')          #SP, cM, n, k
bh_v(x,1,file='test')          #MP, cM, n, k
bh_v(1,save=True,file='test')  #SP, AD, s, k
bh_v(x,save=True,file='test')  #MP, AD, s, k
bh_v(1,1,save=True,file='test')#SP, cM, s, k
bh_v(x,1,save=True,file='test')#MP, cM, s, k
bh_v(1,load=True,file='test')  #SP, AD, l, k
bh_v(x,load=True,file='test')  #MP, AD, l, k
bh_v(1,1,load=True,file='test')#SP, cM, l, k
bh_v(x,1,load=True,file='test')#MP, cM, l, k

Saved.
Saved.
Saved.
Saved.
Saved.
Saved.
Saved.
Saved.


array([0.00207386, 0.00146644, 0.00119735, 0.00103693, 0.00092746,
       0.00084665, 0.00078385, 0.00073322, 0.00069129, 0.00065581])

In [6]:
#Bulge
#Not going to show every combination this time as all functions mirror each other in structure,
#Especially the velocity functions
b_gammafunc(x)
b_I0()
b_r0()
b_innerintegral(1) #Integration not meant to be called for an array
b_vsquare(1)       #Not yet vectorized
b_vsquarev(x)
b_v(x)
b_v(x,save=True)
b_v(x,load=True)

Saved.


array([ 98.13455801, 115.47180352, 122.77457159, 126.05178047,
       127.29905111, 127.40236048, 126.81950423, 125.81052649,
       124.53298597, 123.08685795])

In [7]:
#Halo
h_rhat(x,x)
h_rho(x)
h_vcasertano(x,x)
h_vjimenez(x)
h_vNFW(x)
h_viso(x)
h_v(x)
h_v(x,save=True)
h_v(x,load=True)

Saved.
Saved.


array([ 65.75149178, 103.77632898, 124.32996298, 136.58095041,
       144.58856541, 150.19737518, 154.33299082, 157.50368289,
       160.00971567, 162.03918498])

In [8]:
#Disk
z0(1)
R(1)
d(1)
d_px(x,x,x)
d_rho0(x)
d_durho0(x)
d_rho_rz(x,x)
d_drho_rz(x,x)
d_K(x,x,x)
d_innerfunc(x,x,x)
d_innerintegral(1,1)
d_outerintegral(1)
d_Mdblintrho()
d_F(1)
d_v(x)
d_v(x,save=True)
d_v(x,load=True)

Saved.


array([302.07923368, 406.17769247, 472.76888526, 518.59012522,
       550.59621721, 572.5969578 , 586.9975347 , 595.45386172,
       599.17375706, 599.07467767])

In [9]:
#Total
v(x)
v(x,save=True)
v(x,load=True)

Saved.
Saved.
Saved.
Saved.


array([18.48746711, 21.01102711, 22.53555264, 23.52696447, 24.19321248,
       24.63978187, 24.92771731, 25.09588784, 25.17081789, 25.1715664 ])